import type { CSSProperties } from 'react';
import sky from './poster/sky.svg?raw';
import clouds from './poster/clouds.svg?raw';
import sun from './poster/sun.svg?raw';
import ring from './poster/ring.svg?raw';
import hills from './poster/hills.svg?raw';
import flora from './poster/flora.svg?raw';

/*
 * The cover illustration: a dusk in the field, drawn flat, the way a riso
 * print would be. A gradient sky with a halftone band at the horizon, a few
 * birds, lens-shaped clouds; a grainy sun wearing a dial of forty-two ticks
 * (the six weeks of the longest study, every seventh tick longer); five
 * ridges of hills, each with a lit rim and a contour line, far trees on the
 * second; and in the foreground grasses, cattails, leaves and seed heads.
 * After dark the sun becomes a moon, the stars come out and the palette goes
 * blue — all of it through the --pz-* variables on the plate.
 *
 * The drawing is generated by scripts/poster/make_poster.py into the six SVGs
 * next to this file, one per layer. They are stacked here rather than merged
 * into one SVG so that the pointer parallax, the scroll drift, the clouds'
 * slide and the grasses' sway are each a compositor-only transform on a whole
 * layer. Nothing is filtered, nothing animates inside a layer.
 */
const html = (markup: string) => ({ __html: markup });

export function Poster({ className = '', style }: { className?: string; style?: CSSProperties }) {
  return (
    <div className={`poster ${className}`.trim()} style={style} aria-hidden="true">
      <div className="poster__layer poster__par poster__par--sky" dangerouslySetInnerHTML={html(sky)} />
      <div className="poster__layer poster__glow" />
      <div className="poster__layer poster__par poster__par--clouds" dangerouslySetInnerHTML={html(clouds)} />
      <div className="poster__layer poster__par poster__par--sun" dangerouslySetInnerHTML={html(sun + ring)} />
      <div className="poster__layer poster__par poster__par--hills" dangerouslySetInnerHTML={html(hills)} />
      <div className="poster__layer poster__par poster__par--flora" dangerouslySetInnerHTML={html(flora)} />
      <div className="poster__layer poster__grain" />
    </div>
  );
}
