import imageSizes from './imageSizes.json';

const base = import.meta.env.BASE_URL;

/** Assets exported for the designer mode (public/images/design). */
export const img = (path: string) => `${base}images/design/${path}`;

/** Figures that already ship with the researcher mode (public/images/projects). */
export const sharedImg = (path: string) => `${base}images/projects/${path}`;

/** Link into the researcher mode, e.g. a project reader. */
export const researchHref = (hash = '') => `${base}${hash}`;

/**
 * Intrinsic size for an image URL, spread onto <img> so the browser can reserve
 * the right space before a lazy image loads. The table is generated by
 * `node scripts/design-image-sizes.mjs`; unknown files simply get no attributes.
 */
const sizes = imageSizes as Record<string, number[] | undefined>;
export function sizeOf(src: string): { width?: number; height?: number } {
  const size = sizes[src.slice(src.indexOf('images/') + 'images/'.length)];
  return size ? { width: size[0], height: size[1] } : {};
}
